In [1]:
import pandas as pd
import os
import numpy as np
from matplotlib import pyplot as plt
%matplotlib inline

In [2]:
results_path='../../../griffin_paper/Ulz_nucleosome_profiling/'
metadata_path = '../../metadata/MBC/merged_tables_revisions1/merged_key_metadata.txt'

output_path = 'merged_data/Ulz_MBC_merged.txt'

In [3]:
'../../../griffin_paper/Ulz_nucleosome_profiling/MBC_1421_3_ULP/AccessibilityOutput/MBC_1421_3_ULP_Accessibility1KSitesAdjusted.txt'

'../../../griffin_paper/Ulz_nucleosome_profiling/MBC_1421_3_ULP/AccessibilityOutput/MBC_1421_3_ULP_Accessibility1KSitesAdjusted.txt'

In [4]:
results=pd.DataFrame()
for item in os.listdir(results_path): #import the results
    if item.startswith('MBC'):
        result_file = results_path+item+'/AccessibilityOutput/'+item+'_Accessibility1KSitesAdjusted.txt'
        current=pd.read_csv(result_file, sep='\t')
        current[['TF_name','number_sites','extra_stuff']]=current['TF_profile'].str.rsplit('.', n=2, expand=True)
        current = current[['TF_name','HighFreqRange']]

        current  = current.set_index('TF_name').T.reset_index(drop=True)
        current['sample']=item

        results = results.append(current, ignore_index=True)
features = results.set_index('sample').columns 
print('features', len(features))

features 504

In [5]:
print(len(results))
results.head()

330

TF_name,ADNP,AEBP2,AhR,Androgen,AP-2&#945;,AP-2&#947;,AP-4,ARID1A,ARID1B,ARID2,...,ZNF85,ZNF8,ZNF92,ZSCAN16,ZSCAN22,ZSCAN2,ZSCAN5A,ZSCAN5D,ZXDC,sample
0,0.478289,0.983526,0.513220,0.528512,0.643809,0.470970,0.597685,0.546724,0.978604,0.640062,...,0.808067,0.669372,0.634011,0.909090,0.582475,0.600768,0.652913,0.564368,0.614213,MBC_1421_3_ULP
1,0.557006,0.718111,0.489898,0.756099,0.654748,0.694961,0.510930,0.675768,1.135070,0.582858,...,0.615474,0.552531,0.473985,0.742554,0.758955,0.554572,0.868340,0.738923,0.802368,MBC_1136_3_ULP
2,0.423172,0.585631,0.449372,0.686116,0.336789,0.392084,0.344668,0.320355,0.401246,0.818051,...,0.732517,0.405531,0.396598,0.478459,0.456932,0.395695,0.581046,0.270073,0.320236,MBC_1132_ULP
3,0.408057,0.742235,0.676427,0.578245,0.401718,0.542795,0.533005,0.428124,0.471673,0.504744,...,0.596250,0.507264,0.546727,0.601577,0.345151,0.711717,0.478801,0.467046,0.435319,MBC_291.ctDNA_ULP
4,0.502186,0.923496,0.604358,0.732643,0.600158,0.620168,0.893388,0.609114,0.612445,0.495427,...,0.433482,0.813337,0.721258,0.739612,0.513269,0.516629,0.627361,0.542181,0.661132,MBC_1228_2_ULP

In [6]:
metadata = pd.read_csv(metadata_path, sep='\t')

In [7]:
metadata.head()

,sample,patient_id,TNBC_ULPWGS_ID,PatientID_09204,PatientID_05246,tumor_fraction,ulp_wgs_coverage,merged_PrimaryEstrogenStatus,merged_MetsEstrogenStatus,merged_ER_switch,revisions_ER_status,revisions_ER_status_binary,merged_TimeFromMet_ToDeathOrLastFU_Days,merged_DeathCensor,first_passing_sample
0,MBC_349.ctDNA_T2_ULP,MBC_349,NaN,NaN,05246_349,0.4539,0.149444,+,+,same,+,+,2986.0,1.0,NaN
1,MBC_349.ctDNA_ULP,MBC_349,NaN,NaN,05246_349,0.4532,0.186545,+,+,same,+,+,2986.0,1.0,1.0
2,MBC_349_4_ULP,MBC_349,NaN,NaN,05246_349,0.3499,0.126762,+,+,same,+,+,2986.0,1.0,NaN
3,MBC_349_5_ULP,MBC_349,NaN,NaN,05246_349,0.7825,0.143094,+,+,same,+,+,2986.0,1.0,NaN
4,MBC_339.ctDNA_ULP,MBC_339,NaN,NaN,05246_339,0.4323,0.117778,+,none,unknown,+,+,695.0,1.0,1.0

In [8]:
merged = results.merge(metadata[['sample','revisions_ER_status_binary','first_passing_sample','tumor_fraction']], on = 'sample')

#rename the feature columns
merged = merged.rename(columns = {m:'Ulz_'+m for m in merged[features].columns})

In [9]:
print(len(merged))
merged.head()

254

,Ulz_ADNP,Ulz_AEBP2,Ulz_AhR,Ulz_Androgen,Ulz_AP-2&#945;,Ulz_AP-2&#947;,Ulz_AP-4,Ulz_ARID1A,Ulz_ARID1B,Ulz_ARID2,...,Ulz_ZSCAN16,Ulz_ZSCAN22,Ulz_ZSCAN2,Ulz_ZSCAN5A,Ulz_ZSCAN5D,Ulz_ZXDC,sample,revisions_ER_status_binary,first_passing_sample,tumor_fraction
0,0.478289,0.983526,0.513220,0.528512,0.643809,0.470970,0.597685,0.546724,0.978604,0.640062,...,0.909090,0.582475,0.600768,0.652913,0.564368,0.614213,MBC_1421_3_ULP,-,NaN,0.05783
1,0.557006,0.718111,0.489898,0.756099,0.654748,0.694961,0.510930,0.675768,1.135070,0.582858,...,0.742554,0.758955,0.554572,0.868340,0.738923,0.802368,MBC_1136_3_ULP,+,1.0,0.06610
2,0.408057,0.742235,0.676427,0.578245,0.401718,0.542795,0.533005,0.428124,0.471673,0.504744,...,0.601577,0.345151,0.711717,0.478801,0.467046,0.435319,MBC_291.ctDNA_ULP,+,NaN,0.36170
3,0.502186,0.923496,0.604358,0.732643,0.600158,0.620168,0.893388,0.609114,0.612445,0.495427,...,0.739612,0.513269,0.516629,0.627361,0.542181,0.661132,MBC_1228_2_ULP,-,1.0,0.07684
4,0.704474,0.721339,0.588221,0.644048,0.783946,0.973267,0.710492,0.694164,0.439072,0.823089,...,0.535150,0.713003,0.521931,0.477136,0.789608,0.580989,MBC_1090_ULP,+,1.0,0.06837

In [10]:
merged.to_csv(output_path,sep='\t',index=False)

In [11]:
#check that there aren't any nulls
merged[['Ulz_'+m for m in features]].isnull().any().any()

False

In [12]:
print(len(merged))
merged.shape

254

(254, 508)

In [13]:
merged[['Ulz_'+feature for feature in features]].shape

(254, 504)